#!/bin/bash
wget http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/2022/04/08/public-2022-04-08.all.masked.nextclade.pangolin.pb.gz
wget http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/2022/04/08/public-2022-04-08.metadata.tsv.gz
